package codec

var PhaseSynonyms = map[string]string{
	"Proposal":        "Proposal",
	"RawProposal":     "Proposal",
	"Propose":         "Proposal",
	"Preprepare":      "Proposal",
	"PrePrepare":      "Proposal",
	"Pre-prepare":     "Proposal",
	"Pre-Prepare":     "Proposal",
	"Announce":        "Proposal",
	"BlockProposal":   "Proposal",
	"InitialProposal": "Proposal",

	"Prevote":         "Prepare",
	"PreVote":         "Prepare",
	"Prepare":         "Prepare",
	"PrepareReq":      "Prepare",
	"PrepareRes":      "Prepare",
	"SignReq":         "Prepare",
	"Validation":      "Prepare",
	"Verification":    "Prepare",
	"Soft-Vote":       "Prepare",
	"PrepareResponse": "Prepare",
	"Accept":          "Prepare",
	"Justify":         "Prepare",
	"HighQC":          "Prepare",
	"PrepareQC":       "Prepare",

	"Vote": "Vote", //HotStuff 등에서 Prepare + Commit

	"Precommit":     "Commit",
	"PreCommit":     "Commit",
	"Pre-Commit":    "Commit",
	"PrecommitVote": "Commit",
	"CommitVote":    "Commit",
	"Vote_Commit":   "Commit",
	"Commit":        "Commit",
	"CommitReq":     "Commit",
	"CommitRes":     "Commit",
	"Finalization":  "Commit",
	"Cert-Vote":     "Commit",
	"CommitQC":      "Commit",
	"QC":            "Commit",
	"QuorumCert":    "Commit",
	"Certify":       "Commit",
	"Confirm":       "Commit",

	"ViewChange":        "ViewChange",
	"View-change":       "ViewChange",
	"RoundChange":       "ViewChange",
	"Instance-Change":   "ViewChange",
	"ViewRotation":      "ViewChange",
	"Next-Vote":         "ViewChange",
	"RequestChangeView": "ViewChange",
	"EpochChange":       "ViewChange",
	"LeaderChange":      "ViewChange",

	"NewView":         "NewView",
	"New-view":        "NewView",
	"NewRound":        "NewView",
	"NewHeight":       "NewView",
	"NewEpoch":        "NewView",
	"RecoveryMessage": "NewView",
	"Recovery":        "NewView",
} //여러 구현체의 메시지 타입명 유의어를 표준 타입명으로 정규화(원본 문자열 -> AbstractMessage.Type)

var FieldSynonyms = map[string]string{
	"height":          "Height",
	"sequence":        "Height",
	"seq":             "Height",
	"seq_num":         "Height",
	"sequence_number": "Height",
	"block_num":       "Height",
	"block_height":    "Height",
	"block_sequence":  "Height",
	"pp_seq_no":       "Height",

	"round":        "Round",
	"round_id":     "Round",
	"round_number": "Round",
	"epoch":        "Round",
	"epoch_number": "Round",

	"view":        "View",
	"view_id":     "View",
	"view_number": "View",

	"block_id":          "BlockHash",
	"block_hash":        "BlockHash",
	"block_header_hash": "BlockHash",
	"block_digest":      "BlockHash",
	"digest":            "BlockHash",
	"message_digest":    "BlockHash",
	"proposal_hash":     "BlockHash",
	"proposal_id":       "BlockHash",

	"prev_hash":       "PrevHash",
	"previous_hash":   "PrevHash",
	"parent_hash":     "PrevHash",
	"last_block_hash": "PrevHash",

	"time":          "Timestamp",
	"timestamp":     "Timestamp",
	"pp_time":       "Timestamp",
	"proposal_time": "Timestamp",
	"created_at":    "Timestamp",
	"creation_time": "Timestamp",

	"proposer":    "Proposer",
	"proposer_id": "Proposer",
	"leader":      "Proposer",
	"leader_id":   "Proposer",
	"primary":     "Proposer",

	"validator":            "Validator",
	"validator_id":         "Validator",
	"validator_public_key": "Validator",
	"validator_address":    "Validator",
	"node_address":         "Validator",
	"node_id":              "Validator",
	"replica_id":           "Validator",
	"signer_id":            "Validator",
	"signer":               "Validator",

	"signature":           "Signature",
	"sig":                 "Signature",
	"sign":                "Signature",
	"commit_seal":         "Signature",
	"bls_sig":             "Signature",
	"validator_signature": "Signature",
	"node_signature":      "Signature",
	"block_signature":     "Signature",
	"message_signature":   "Signature",
	"aggregate_signature": "Signature",

	"commit_seals":      "CommitSeals",
	"seals":             "CommitSeals",
	"commit_signatures": "CommitSeals",

	"view_changes":       "ViewChanges",
	"viewchange_entries": "ViewChanges",
	"vc_entries":         "ViewChanges",
	"justifications":     "ViewChanges",
} //여러 구현체의 필드명 유의어를 표준 필드명으로 정규화
